version: '3'
services:
  db:
    image: mysql:latest
    container_name: blog-backend-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql-data:/var/lib/mysql
