# ---------------------------------------- DEV ---------------------------------------- #
version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: blog-backend-mysql
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
