# ---------------------------------------- DEV ---------------------------------------- #
version: '3'
services:
  db:
    image: mysql:latest
    container_name: blog-backend-mysql
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: blog-backend-redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PWD}
    volumes:
      - redis-data:/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  
volumes:
  mysql-data:
  redis-data:
